### ISSUE TITLE
Project directory issues: cannot open input file

### ISSUE THREAD

**Issue by dkrey** [rosc77/vs64#2]
Hi and thanks for your cool extension.

Unfortunately I have no idea how to define a project directory and vs64 seems to have issues with relative paths.
Using !source "c:/users/dkrey/c64_project/code/main.asm" works, but
!source "code/main.asm does not.

Right now I've opened the project folder via the righ-click context menu.

I also tried to open and compile this tutorial code (which should be fine) and problem persists
https://github.com/actraiser/dust-tutorial-c64-first-intro
Referencing external files via !source doesn't work and results into the error: 'cannot open input file'.

The !to command doesn't work as well and spits out this warning: 'Output file already chosen.'

**Comment by rosc77** [comment]
Thanks for your feedback.

I tried to improve the behavior by adding the base file's directory to ACME's search path. The demo also builds and runs now. Best would probably be to add a settings value to configure search paths (either workspace or even global settings in vscode).

The !to command is currently ignored as the extension has it's own mechanism of building and caching. Look at a ".cache" folder to find the built PRGs. (Best from my point of view would be to not use !to at all as I generally don't think it's good practice to put settings into source files)
