### ISSUE TITLE
Setting program counter during internal emulation

### ISSUE THREAD

**Issue by vsariola** [rosc77/vs64#3]
Hi,

I seem to be able to compile, run using VICE and debug using C64debugger. But I'm struggling to start the internal debugger's PC at $1000, which is the starting address of my program. In debug console, I only get: "Break at $0000", and looking at the PC, this is obviously due to PC = $0000. How to set the starting address of the emulator? As usual, my code starts with something like:

```asm
!cpu 6502
; 10 SYS (4096)
*=$0801
!byte    $0E, $08, $0A, $00, $9E, $20, $28,  $34, $30, $39, $36, $29, $00, $00, $00
*=$1000 
               <here starts the actual code>
```

I'd like to set PC to $1000 when debugging starts, preferably automatically in launch.json, but setting it manually every time I start debugging is manageable solution too.

**Comment by rosc77** [comment]
Hi vsariola,

Thanks for your feedback and great suggestion.

In the latest version 0.1.7 it is possible to set the "pc" in the debugger launch configuration. That setting will define the initial program counter, or overwrite the address information given as the first two bytes of a PRG.

Hope you like it.

Roland

**Comment by rosc77** [comment]
Just for completeness, you could also add the typical sys jump start code:

`

*=$0801
!byte $0c,$08,$b5,$07,$9e,$20,$32,$30,$36,$32,$00,$00,$00
jmp start

; do something here

start

; your code starts here

`
