### ISSUE TITLE
Working on Mac ?

### ISSUE THREAD

**Issue by sneaker333** [rosc77/vs64#4]
I've installed the extension and installed a working binary of acme. I've set up the path to acme in the settings but nothing appears to happen when I save a .asm file. I appear to be getting no errors or messages. Has anyone been using this extension on a Mac ? I cannot see any mention of what platforms are supported and the example settings are obviously Windows examples. It's probably just me and I'm having a bad day.

Many thanks

**Comment by rosc77** [comment]
Hi,

Sorry to hear you've had problems. Unfortunately, I have to admit that I do not have access to Macs - while Windows and Linux are tested, I am currently not able to ensure the Mac platform does work well.

I'd be totally happy if somebody could step in here. In addition, and in case I find enough time, I'll have a look to at least improve the error reporting behaviour.

The only thing to help you at the moment would be the suggestion to turn on "verbosity" at the vs64 plugin settings.

Regards,

Roland

**Comment by vonmillhausen** [comment]
I'm seeing similar behaviour on my own Mac; have Acme set up, and vs64 configured with the correct path to it, but nothing happens when modifying and saving .asm files. If I try to manually call the `C64: Build` or `C64: Run` functions, I just get a pop-up error from VS Code:

![Screenshot 2019-08-03 at 16 04 20](https://user-images.githubusercontent.com/2813243/62413579-601cbb00-b608-11e9-833c-e27b2f2e4529.png)

**Comment by sneaker333** [comment]
Unfortunately I haven't had any time to explore this further myself, but in case it's useful for others the best solution I have found so far for mac, vscode and acme is using this template - https://github.com/Esshahn/acme-assembly-vscode-template

**Comment by rosc77** [comment]
A new release v0.1.8 is out. Not sure if it fixes the issues, but at least a few path handling improvements have been added as well as additional checks of path settings if verbose mode is enabled in the settings.
(Unfortunately: still no possibility for me to test on Mac)

**Comment by vonmillhausen** [comment]
Alas, same issue in v0.1.8 - the build and run commands fail with `command 'c64.build' not found` and `command 'c64.run' not found`. Here's the console log output, in case it's of any use:

![Screenshot 2019-09-02 at 21 59 11](https://user-images.githubusercontent.com/2813243/64133365-72d40c80-cdcd-11e9-9b2e-fb4c66b26524.png)

**Comment by rosc77** [comment]
Version 0.1.9 is out - next try - not easy to work on the problem without a Mac...
Improved/fixed handling of empty workspaces (no folders open) - in this case, conflicting features are disabled (build/run/debug commands and the debugger extension).

**Comment by vonmillhausen** [comment]
> not easy to work on the problem without a Mac...
I can imagine - trying to troubleshoot in the dark :)

I tested with 0.1.9 - still not working, but the behaviour has changed. I'm no longer getting the pop-up `command 'c64.build' not found` messages from Code, and no errors are being logged to Code's developer console (Help > Toggle Developer Tools > Console):

![Screenshot 2019-09-05 at 10 44 43](https://user-images.githubusercontent.com/2813243/64331260-6072f200-cfca-11e9-8403-7197d2404844.png)

However nothing appears to happen when trying to build or run; no pop-up messages from Code, nothing logged to the developer console, no PRG file created, etc.. My "Hello World" script is in a workspace. Are there any details about my environment or configuration that would be useful to you? Or are there any other logs beyond what appears in the developer console that might shed some light? Happy to help in any way I can :)

**Comment by vonmillhausen** [comment]
Success! I found a macOS binary for Acme `0.96.4`, and VS64 is now compiling and running successfully 🎉

One thing I note - it compiles into a `.cache` subfolder of the workspace, not into the folder where the `.asm` file is located. I'm not sure if that's intended behaviour, or a quirk of how VS64 is running on macOS. "Dot" files and folders are hidden by default in macOS' file explorer.

**Comment by rosc77** [comment]
Great! Thanks for your passionate support.

The .cache folder is indeed on purpose - I found that to be the most non-intrusive way to support zero-config / auto-build. And, I like clean folder structures with an easy way to git-ignore parts.

Cheers!

**Comment by vonmillhausen** [comment]
No problem - thank _you_ for the updates that fixed the `command 'c64.build' not found` style errors :)
