### ISSUE TITLE
Ability to specify parameters for emulator and debugger

### ISSUE THREAD

**Issue by andremiller** [rosc77/vs64#9]
Is there a way to specify some parameters that are passed to Vice or C64 Debugger?

For example, I would like to specify "-autostartprgmode 1" when running Vice. This injects the PRG directly into RAM when Vice starts up, skipping the program load step.

I tried specifying it as such in the settings:
C64: Emulator Path : C:\dev\c64\vice\x64sc.exe -autostartprgmode 1

But that fails with 'failed to start' message when I trigger C64: Run

**Comment by rosc77** [comment]
Hi Andre,

Thanks for the request - great suggestion. As soon as spare time allows, I'll have a look.

Roland

**Comment by rosc77** [comment]
Hi Andre,

Maybe you want to give the new preview version 0.1.10 a try...

Cheers!
Roland

**Comment by andremiller** [comment]
Wow, that was quick, thank you very much!
Apologies for only taking so long to respond, I just had a chance to test it and it works great.
Specifying "-autostartprgmode 1" as the C64: Emulator args launches the program much faster.
